CREATE DATABASE ESTUDIO;

CREATE TABLE ALUMNOS(
	ID VARCHAR(12) NOT NULL,
	USUARIO VARCHAR(12) NOT NULL,
	CONTRASEÑA VARCHAR(12) NOT NULL,
	NOMBRE VARCHAR(30) NOT NULL,
	APELLIDO1 VARCHAR(30) NOT NULL,
	APELLIDO2 VARCHAR(30) NOT NULL,
	CURSO VARCHAR(30) NOT NULL,
	NIVEL VARCHAR(30) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE TEMAS(
	ID VARCHAR(12) NOT NULL,
	NOMBRE VARCHAR(30) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE PREG_DEFINICIONES(
	ID VARCHAR(12) NOT NULL,
	ID_TEMA VARCHAR(12) NOT NULL,
	PREGUNTA VARCHAR(100) NOT NULL,
	RESPUESTA VARCHAR(1000) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY ID_TEMA REFERENCES TEMAS(ID)
);

CREATE TABLE PREG_OPCION_UNICA(
	ID VARCHAR(12) NOT NULL,
	ID_TEMA VARCHAR(12) NOT NULL,
	PREGUNTA VARCHAR(100) NOT NULL,
	RESPUESTA1 VARCHAR(30) NOT NULL,
	RESPUESTA2 VARCHAR(30) NOT NULL,
	RESPUESTA3 VARCHAR(30) NOT NULL,
	CORRECTA VARCHAR(10) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY ID_TEMA REFERENCES TEMAS(ID)
);

CREATE TABLE PRE_OPCION_MULTIPLE(
	ID VARCHAR(12) NOT NULL,
	ID_TEMA VARCHAR(12) NOT NULL,
	PREGUNTA VARCHAR(100) NOT NULL,
	RESPUESTA1 VARCHAR(30) NOT NULL,
	RESPUESTA2 VARCHAR(30) NOT NULL,
	RESPUESTA3 VARCHAR(30) NOT NULL,
	RESPUESTA4 VARCHAR(30) NOT NULL,
	RESPUESTA5 VARCHAR(30) NOT NULL,
	CORRECTA1 BOOLEAN NOT NULL,
	CORRECTA2 BOOLEAN NOT NULL,
	CORRECTA3 BOOLEAN NOT NULL,
	CORRECTA4 BOOLEAN NOT NULL,
	CORRECTA5 BOOLEAN NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY ID_TEMA REFERENCES TEMAS(ID)
);
